---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.license.self_generated.type: basic
xpack.security.enabled: false

## Search Guard
#
#searchguard.enterprise_modules_enabled: true

#searchguard.ssl.transport.keystore_filepath: sg/node-0-keystore.jks
#searchguard.ssl.transport.truststore_filepath: sg/truststore.jks
#searchguard.ssl.transport.enforce_hostname_verification: false

#searchguard.authcz.admin_dn:
#  - "CN=kirk,OU=client,O=client,l=tEst,C=De"
searchguard.ssl.transport.pemcert_filepath: sg/certificates/esnode.pem
searchguard.ssl.transport.pemkey_filepath: sg/certificates/esnode-key.pem
searchguard.ssl.transport.pemtrustedcas_filepath: sg/certificates/root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: sg/certificates/esnode.pem
searchguard.ssl.http.pemkey_filepath: sg/certificates/esnode-key.pem
searchguard.ssl.http.pemtrustedcas_filepath: sg/certificates/root-ca.pem
searchguard.allow_unsafe_democertificates: true
searchguard.allow_default_init_sgindex: true
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test,C=de

  