---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true


xpack.security.enabled: false

## Search Guard
#
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver

searchguard.cookie.password: 123567818187654rwrwfsfshdhdhtegdhfzftdhncn
elasticsearch.ssl.verificationMode: none
